[project]
name = "reentry-eikonal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Simone Pezzuto", email = "simone.pezzuto@unitn.it" }
]
requires-python = ">=3.14"
dependencies = [
    "h5py>=3.16.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "meshio>=5.3.5",
    "numpy>=2.5.1",
    "petsc4py>=3.25.4",
    "pyvista>=0.48.4",
    "scikit-fmm>=2025.6.23",
    "scipy>=1.18.0",
    "tqdm>=4.70.0",
]
