/*
 * $Id: Functions.h,v 1.3 2006/12/20 12:25:31 potse Exp $
 *
 * $Log: Functions.h,v $
 * Revision 1.3  2006/12/20 12:25:31  potse
 * warn at compile time if declaration of the allocation routines seems
 * to be missing
 *
 *
 *
 */

/*
 * if none of these is defined, assume we have to declare 
 * malloc() etc. 
 * - wrote someone before me.  I think that this only occurs
 * when the user failed to #include <stdlib.h> before including
 * a parameter file, so a warning is more appropriate (MP 12/2006).
 */
#ifndef __MALLOC_H__
#ifndef __STDLIB_H__           	/* for IRIX */
#ifndef _STDLIB_H            	/* for Linux */
#ifndef __malloc_h
#ifndef __stdlib_h
#ifndef _INC_MALLOC
#ifndef _H_STDLIB              	/* for /usr/include/stdlib.h on AIX */
#ifndef _STDLIB_H_				/* for Mac OS X */

char	*calloc();
void	free();
char	*malloc();
char	*realloc();
#warning "should #include stdlib.h before PRM #includes"

#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif

/* There used to be a declaration "int param();" here
 * but I don't know why; the function ought to be declared in
 * a header file generated by the param program, with all the
 * application-dependent arguments. C compilers seem to allow
 * an initial declaration without arguments, the Gnu C++ compiler
 * version 10 does not.
 */

#ifdef __STDC__
char	*PrMnewstr(char*);
char	*PrMrequote(char*);
Text	PrMaddline(Text, char*);
Text	PrMgeterrortext(void);
Text	PrMnewtext(void);
void	PrMadderror(char*);
void	PrMclearerrors(void);
void	PrMprinterrors(void);
void	PrMquote(char*);
void	PrMunquote(char*);
void	PrMusage(char*, char*);
#else 
char	*PrMnewstr(/* char* */);
char	*PrMrequote(/* char* */);
Text	PrMaddline(/* Text, char* */);
Text	PrMgeterrortext(/* void */);
Text	PrMnewtext(/* void */);
void	PrMadderror(/* char* */);
void	PrMclearerrors(/* void */);
void	PrMprinterrors(/* void */);
void	PrMquote(/* char* */);
void	PrMunquote(/* char* */);
void	PrMusage(/* char*, char* */);
#endif

#ifdef MOTIF
int	PrMmotif();
#endif

